### ISSUE TITLE
install gulp globally

### ISSUE THREAD

**Issue by digiltd** [outeredge/edge-docker-php-dev#1]
using `node_modules/gulp/bin/gulp.js` is a bit of a mouthful, installing `gulp-cli`globally (`npm install -g gulp-cli`)should fix that, but regular users don't have the permissions to do so.

**Comment by davidwindell** [comment]
Implemented in https://github.com/outeredge/edge-docker-php/commit/9a75fb0f270490243600f073b983b9026a448b66
